# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'Example' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  	pod 'zichenPodSpec', :path => '../'
  # Pods for Example

  target 'ExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
